INSERT INTO companies (id,name,specification_verbatim,profession_verbatim,prof_category_id,bold,advert) VALUES 
( '1','Comp',null,'Commissionsgeschäft','4',null,null ),
( '2','Comp',null,'Handelscommissionär','4',null,null ),
( '3','Comp',null,'Commissions- u. Speditionshandel','4',null,null ),
( '4','Comp',null,'Seidewaaren, Versendungen','4',null,null ),
( '5','Comp',null,'Commissionsgeschäft','4',null,null ),
( '6','Comp',null,'Damenkleider-Anzüge','4',null,null ),
( '7','Comp',null,'Commissions-Handlung','4',null,null ),
( '8','Lindemann J Szanne Comp',null,'Besorgung in Aufträgen für Zuckerwaaren','4',null,null ),
( '9','Comp',null,'Verfertigte Kleidungsstücke','4',null,null ),
( '10','Comp',null,'Bankier','11',null,null ),
( '11','Comp',null,'Bankier','4',null,null ),
( '12','Sen Comp',null,'Niederlage ihrer Klingenthaler Gewehrfabrik','5',null,null ),
( '13','Comp',null,'Porcelanmaler u. Drucker','5',null,null ),
( '14','Comp H Leclse-lepley Et Cie Sccessers',null,'Hutmachereiartikel','4',null,null ),
( '15','Comp',null,'Commissionsgeschäft in Waaren, Versendungen','4',null,null ),
( '16','Comp',null,'Vergoldung, Versilberung und Manufactur von Goldarbeiten , alleinige Eigenthümer der Brevet der HH. Elkington u. von Ruolz','5',null,null ),
( '17','Comp',null,'Tapezierer u. Schreiner','5',null,null ),
( '18','Comp',null,'Weinhändler','4',null,null ),
( '19','Comp',null,'Besorgung für Straßenfuhrwerke','4',null,null ),
( '20','Comp',null,'Directoren der Kunstschreinerzunft','11',null,null ),
( '21','Comp',null,'Stickereien','5',null,null ),
( '22','Comp Nachfolger Von Rox Carré',null,'Merino und Modewaaren','4',null,null ),
( '23','Comp',null,'Ochsenfußölfabrik','5',null,null ),
( '24','Theilhaber Des Hases Destrem Mallet Ragel Comp',null,'Theilhaber','4',null,null ),
( '25','Comp',null,'Klaviermacher','5',null,null ),
( '26','Comp',null,'Waagenmacher','5',null,null ),
( '27','Ggenheim Léon Wwe Comp',null,'Weißwaaren u. Stickereien','4',null,null ),
( '28','Comp',null,'Nachfolger von Letourneau, Leuchtthurmbaumeister','10',null,null ),
( '29','Comp',null,'Eisen und Maschinen','4',null,null ),
( '30','Comp',null,'Bankier','4',null,null ),
( '31','Vonom Hase Wittwe Platel Comp',null,null,null,null,null ),
( '32','Comp',null,'Strohhutfabrikant','5',null,null ),
( '33','Comp',null,'Papierhandel und Pumpen-Tintenfässerfabrik','4',null,null ),
( '34','Comp',null,'Klavierfabrik','5',null,null ),
( '35','Comp',null,'Commissionsgeschäft','10',null,null ),
( '36','Comp',null,'Uhrmacher','5',null,null ),
( '37','Comp',null,'Waagefabrik','5',null,null ),
( '38','Comp',null,'Schreibmaterialen','4',null,null ),
( '39','Comp',null,'Schalenfabrik','5',null,null ),
( '40','Comp',null,'Porzellanhandlung','4',null,null ),
( '41','Gebrüder Hber Comp',null,'Fabrik von Plüsch für die Hutmacher','5',null,null ),
( '42','Comp',null,'Electrisch-medicinische Apparate','4',null,null ),
( '43','Comp',null,'Spitzenfabrik','5',null,null ),
( '44','Comp',null,'Tuch- und Hutfabrik','5',null,null ),
( '45','Hecht Gebr Comp',null,'Rohstoffe für Kunstdrechsler','4',null,null ),
( '46','Comp',null,'Kappenmacher','5',null,null ),
( '47','Comp',null,'Nadelfabrik','5',null,null ),
( '48','Neffe Comp',null,'Schuhwerk','5',null,null ),
( '49','Sohn Comp',null,'Klaviermacher','5',null,null ),
( '50','Comp',null,'Ebenholz-Fabrik','5',null,null ),
( '51','Comp',null,'Waffenschmied','5',null,null ),
( '52','Comp',null,'Schneider','5',null,null ),
( '53','Comp',null,'Civilbaumeister','10',null,null ),
( '54','Comp',null,'Blumenfabrik','5',null,null ),
( '55','Comp',null,'Baumwollenzeug','4',null,null ),
( '56','Fra Comp',null,'Modeartikel','4',null,null ),
( '57','Comp',null,'Porzellanwaaren','4',null,null ),
( '58','Comp',null,'Mützenmacherei und Furnituren für Hutmacher','5',null,null ),
( '59','Comp',null,'Kammmacher','5',null,null ),
( '60','Comp',null,'Speditionshandel','4',null,null ),
( '61','Comp',null,'Federn und Schlösser für Wagen und Eisenbahnen','5',null,null ),
( '62','Comp',null,'Fabrikant v. hydraulischem Kalk','4',null,null ),
( '63','Comp',null,'Orgelbauer','5',null,null ),
( '64','Comp',null,'Apparate für Daguerreotyp-Bilder / Lichtbildermaler','4',null,null ),
( '65','Comp',null,'Gesellschaft für Anfertigung musikalischer Messing- und Holzinstrumente','10',null,null ),
( '66','Comp',null,'Comptoir für die Umsetzung der Industriepapiere','4',null,null ),
( '67','Comp',null,'Holländische Käse u. feine Branntweine','4',null,null ),
( '68','Comp',null,'Schneider','5',null,null ),
( '69','Comp',null,'Juwelenhandel','4',null,null ),
( '70','Vater Comp',null,'Mechanicus, Bleigießer u. Spitzenmacher','5',null,null ),
( '71','Jn Comp',null,'Kaufmann','4',null,null ),
( '72','Witwe Comp',null,'Hosenträger-, Strumpfbänder-,Börsen-, Taschen- und Kamaschen-Fabrikant','5',null,null ),
( '73','Comp',null,'Kaufleute, Bronce u. Ultramarin','4',null,null ),
( '74','Comp',null,'Fab. de mastic Dihl','5',null,null ),
( '75','Franck Jn Comp',null,'Modewaaren','4',null,null ),
( '76','Comp',null,'Commissions- u. Lithographiesteinhandel','4',null,null ),
( '77','Comp',null,'Korsetten, Hemden, Weißzeughandlung','4',null,null ),
( '78','Pollock Comp Vonertreten Vonon E Delevoninge',null,'Commissionäre','4',null,null ),
( '79','Comp',null,'Standuhrensockelfabrik','5',null,null ),
( '80','Comp',null,'Gasmesserfabrik','5',null,null ),
( '81','Comp',null,'Eisengießerei','5',null,null ),
( '82','Comp',null,'Säckler u. Mützenmacher','5',null,null ),
( '83','Comp',null,'Artikel für Schneider','4',null,null ),
( '84','Comp',null,'Handschuhfabrik','5',null,null ),
( '85','Comp',null,'Wachstuchhandel','4',null,null ),
( '86','Comp',null,'Stoffwäscherei','5',null,null ),
( '87','Comp',null,'Bankier','4',null,null ),
( '88','Comp',null,'Bankier','4',null,null ),
( '89','Comp',null,'Baumeister u. Errichter von Gaswerken','10',null,null ),
( '90','Comp',null,'Stoffdruckerei','5',null,null ),
( '91','Comp',null,'Artikel von Rouen im Großen','4',null,null ),
( '92','Comp',null,'Brieftaschen u. Etuis','4',null,null ),
( '93','Sen Comp',null,'Artikel von Rouen','4',null,null ),
( '94','Comp',null,'Mechaniker','5',null,null ),
( '95','Oeschger Meßbach Comp',null,'Metallhandel','4',null,null ),
( '96','Comp',null,'Stoffdruckerei','5',null,null ),
( '97','Comp',null,'Commissionär','4',null,null ),
( '98','Comp',null,'Unternehmer der Ausleerung','10',null,null ),
( '99','Comp',null,'Geruchlose Reinigung der Abtritte','10',null,null ),
( '100','Comp',null,'Klaviermacher','5',null,null ),
( '101','Gebrüder Comp',null,'Commissionsgeschäft in gewirkten Waaren','4',null,null ),
( '102','Comp',null,'Pelzwaaren','4',null,null ),
( '103','Jn Comp',null,'Commissionsgeschäft in Uhren','4',null,null ),
( '104','Comp',null,'Buchhandlung u. Lesekabinet','4',null,null ),
( '105','Comp',null,'Geldwechsler','4',null,null ),
( '106','Comp',null,'Kaffeehaus Thoniach','10',null,null ),
( '107','Comp',null,'Wagner','5',null,null ),
( '108','Comp',null,'Papier-Niederlage','4',null,null ),
( '109','Comp',null,'Commissionär','4',null,null ),
( '110','Comp',null,'Brennholtz, Stein- u. Holzkohlenhandel','4',null,null ),
( '111','Comp',null,'Weinhandlung in Großem','4',null,null ),
( '112','Comp',null,'Handelsmann','4',null,null ),
( '113','Comp',null,'Bankier','4',null,null ),
( '114','Comp',null,'Brüderschafts-Verein v. den Limonade-Händlern zur Großen Familie','10',null,null ),
( '115','Comp',null,'Thürschließer','5',null,null ),
( '116','Sohn Comp Vonon Mühlhasen',null,null,'4',null,null ),
( '117','Comp',null,'Buchbinder','5',null,null ),
( '118','Comp',null,'Ungarische Ledergerberei','5',null,null ),
( '119','Wtb Urban Stterlin Comp',null,'Unternehmer und Eigenthümer der Manufactur von Mutzig, Depot','10',null,null ),
( '120','Comp',null,'Commissions- u. Speditionsgeschäft','4',null,null ),
( '121','Comp',null,'Eigenthümer von Granitbrüchen','4',null,null ),
( '122','Comp',null,'Fabrik v. Farbehözern','5',null,null ),
( '123','Comp',null,'Papierhandlung','4',null,null ),
( '124','Comp',null,'Töpfefabrik','5',null,null ),
( '125','Comp',null,'Bankier','4',null,null ),
( '126','Comp',null,'Repräsentanten verschiedener Häuser Deutschlands, Belgiens u. der Schweiz','4',null,null ),
( '127','Comp',null,'Bankier','4',null,null ),
( '128','Comp',null,'Bankier','4',null,null ),
( '129','Comp',null,'Lithographiestein-Handlung','4',null,null ),
( '130','Comp',null,'Buchhandel im Großen','4',null,null ),
( '131','Comp',null,'Fremde Wollwaaren','4',null,null ),
( '132','Comp',null,'Bankier- und Commissionshandel','4',null,null ),
( '133','Gebrüder Comp',null,'Waaren-Commissionäre','4',null,null ),
( '134','Comp',null,null,'4',null,null ),
( '135','Comp',null,'Commissionsgeschäft','4',null,null ),
( '136','Comp',null,'Artikel von Paris','4',null,null ),
( '137','Comp',null,'Stein- und Buchdruckerei','5',null,null ),
( '138','Comp',null,'Bankier','4',null,null ),
( '139','Comp',null,'Lichtschirm- und geographische Reliefkarten-Fabrik','5',null,null ),
( '140','Comp',null,'Spiegel- u. Fensterglas','4',null,null )